runtime: python39
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

env_variables:
  CLOUDSQL_CONNECTION_NAME: csesamscenter-2022:us-east4:csesdb22
  CLOUDSQL_USER:
  CLOUDSQL_PASSWORD:

libraries:
- name: MySQLdb
  version: latest